SELECT
  L.ID AS 'Location ID',
  L.START_DATE AS 'Start Date',
  L.END_DATE AS 'End Date',
  L.TOTAL AS 'Total',
  C.NAME AS 'Client',
  AUT.NAME AS 'Vehicle',
  E.NAME AS 'Employee'
FROM
  LOCATIONS AS L
  INNER JOIN CUSTOMERS AS C ON (L.CUSTOMER_ID = C.ID)
  INNER JOIN CARS AS AUT ON (L.CAR_ID = AUT.ID)
  INNER JOIN EMPLOYEES AS E ON (L.EMPLOYEE_ID = E.ID);